### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by burgarth** [ddvk/remarkable-autoinstall#1]
This works really nicely. Do you think you can include your fork of fingerterm in this autoinstall?

**Comment by burgarth** [comment]
Wow, that was so quick, thanks a lot! I was hoping to use vim on fingerterm, but it does a full screen refresh every 5 keystrokes or so. That's probably hard to change?

**Comment by ddvk** [comment]
it depends, it could be made much better, but i dont know when i will have
time to do it

**Comment by burgarth** [comment]
No worries, you already do so much amazing stuff, and perhaps I am the only person in the universe using this. My ultimate dream is a small latex installation with vim :) Anyway I close this for the time being. Cheers, Daniel

**Comment by dzikitomek** [comment]
Thanks for this. Everything (quick installer and koreader) seem to work perfectly on a ReMarkable 2 with 2.5 firmware and ddvk remarkable-hacks previously installed. 

That literally changes this device completely, as the original ebook reader is unusable in most cases.
