### ISSUE TITLE
RM2: needs updated rm2fb for version 2.6

### ISSUE THREAD

**Issue by jannes** [ddvk/remarkable-autoinstall#15]
The autoinstall script for RM2 needs to install the updated rm2fb
version when installing on 2.6. I don't see the new rm2fb available as
binary release yet, so that needs to be available first to resolve this issue.

**Comment by ddvk** [comment]
i'm running 2.6 and the binaries still work, that is for koreader

**Comment by jannes** [comment]
So I just realized the 2.6 update removed the touchinjector service and after reinstalling with the current script it all works. Sorry, when the swipe gesture to open Koreader didn't work anymore and I read on the other repos something about rm2fb not working, I jumped to a conclusion here. 

Thanks for your help:)
