### ISSUE TITLE
Long swipe up to switch to KOReader stopped working with 2.9.1.217 update

### ISSUE THREAD

**Issue by juanfcocontreras** [ddvk/remarkable-autoinstall#19]
With the latest version of Remarkable (it was working with 2.9.0.210, but not now with 2.9.1.217), I can no longer launch KOReader by swiping up. If I launch by ssh `/root/scripts/swipeup.sh`, it is still working.

I've also checked that touchinjector service is reinstalled and running:

```
 touchinjector.service - touch injector
     Loaded: loaded (/etc/systemd/system/touchinjector.service; enabled; vendor preset: disabled)
     Active: active (running) since Fri 2021-08-27 17:40:07 CEST; 16min ago
   Main PID: 232 (touchinjector)
     CGroup: /system.slice/touchinjector.service

232 /home/root/apps/touchinjector
Aug 27 17:40:07 reMarkable systemd[1]: Started touch injector.
```

If I try to launch `touchinjector` directly, it seems that is also working:

```
reMarkable: ~/apps/ ./touchinjector
touchinjector 0.0.4-6-g168cfb5
```

Any idea of what is going on?

**Comment by juanfcocontreras** [comment]
I am reopening this issue because I have already found the problem, although I don't know how to solve it.

It seems that the service, although apparently started correctly, is not working. Once the service is restarted by ssh, it starts working without problem. You can switch between the interface and KOReader as many times as you want, until you do a complete restart, where the problem returns again.

This is the output of the service that just started the remarkable and does not work:

```
● touchinjector.service - touch injector
     Loaded: loaded (/etc/systemd/system/touchinjector.service; enabled; vendor
preset: disabled)
     Active: active (running) since Mon 2021-08-30 13:33:48 CEST; 1min 24s ago
   Main PID: 226 (touchinjector)
     CGroup: /system.slice/touchinjector.service
             └─226 /home/root/apps/touchinjector

Aug 30 13:33:48 reMarkable systemd[1]: Started touch injector.
```

And after running `systemctl restart touchinjector`, the output is:

```
● touchinjector.service - touch injector
     Loaded: loaded (/etc/systemd/system/touchinjector.service; enabled; vendor
preset: disabled)
     Active: active (running) since Mon 2021-08-30 13:35:37 CEST; 10s ago
   Main PID: 300 (touchinjector)
     CGroup: /system.slice/touchinjector.service
             └─300 /home/root/apps/touchinjector

Aug 30 13:35:37 reMarkable systemd[1]: Started touch injector.
```

I don't find any noticeable difference. Does anyone know what could be going on?

**Comment by fedecupe** [comment]
Getting the same issue, let me know if you need anything else to debug.

**Comment by ddvk** [comment]
rm1 or rm2?

**Comment by juanfcocontreras** [comment]
> rm1 or rm2?

rm2

**Comment by ddvk** [comment]
try installing it again, it seems rm2fb had to be updated

**Comment by juanfcocontreras** [comment]
> try installing it again, it seems rm2fb had to be updated

I have installed version 0.0.7, which I think is the latest version available.

Maybe it is a problem because service is launching too soon? If I restart it manually, it works well.

**Comment by KYG-yaya573142** [comment]
Seems similar to the [remux issue](https://github.com/rmkit-dev/rmkit/issues/141) after RM2 ver 2.9.
I've tried the solution [mentioned by matteodelabre](https://github.com/rmkit-dev/rmkit/issues/141#issuecomment-908304976) and seems to solve the issue.
First make systemd to track input devices by adding the file `/lib/udev/rules.d/15-systemd-input.rules` with the following content.
```
ACTION=="add", SUBSYSTEM=="input", TAG+="systemd"
```

Then modified `/etc/systemd/system/touchinjector.service` to start after input devices.
```diff
[Unit]
    Description=touch injector
-   After=home.mount
+   Requires=dev-input-event0.device dev-input-event1.device dev-input-event2.de
+   After=home.mount dev-input-event0.device dev-input-event1.device dev-input-e
```

**Comment by ddvk** [comment]
I added this to the installer

**Comment by juanfcocontreras** [comment]
> Seems similar to the [remux issue](https://github.com/rmkit-dev/rmkit/issues/141) after RM2 ver 2.9.
> I've tried the solution [mentioned by matteodelabre](https://github.com/rmkit-dev/rmkit/issues/141#issuecomment-908304976) and seems to solve the issue.
> First make systemd to track input devices by adding the file `/lib/udev/rules.d/15-systemd-input.rules` with the following content.
> 
> ```
> ACTION=="add", SUBSYSTEM=="input", TAG+="systemd"
> ```
> 
> Then modified `/etc/systemd/system/touchinjector.service` to start after input devices.
> 
> ```diff
> [Unit]
>     Description=touch injector
> -   After=home.mount
> +   Requires=dev-input-event0.device dev-input-event1.device dev-input-event2.de
> +   After=home.mount dev-input-event0.device dev-input-event1.device dev-input-event2.device
> ```

It is working great here!! Thank you very much @KYG-yaya573142, and @ddvk for integrating the solution. Close this issue.
