### ISSUE TITLE
Missing address for function 'getInstance' error on 2.10.3.379

### ISSUE THREAD

**Issue by bufferbandit** [ddvk/remarkable-autoinstall#22]
Hi,

When I'm trying to use this on version 2.10.3.379 on my rM2, I'm getting the error: Missing address for function 'getInstance'
How do I fix this?

Thanks in advance.

**Comment by ddvk** [comment]
the other projects has to be updated first..

**Comment by bufferbandit** [comment]
Hi, what software? RM2FB I suppose?

**Comment by briankaemingk** [comment]
I believe so... @ddvk can correct me if I'm wrong, but it looks like progress is being made for this version as of 3 days ago [in this issue](https://github.com/ddvk/remarkable2-framebuffer/issues/18). Once they build/release that, then we'll need to update this project pointing to that latest release, then this should be resolved.

**Comment by bufferbandit** [comment]
That'd be awesome. I'll keep an eye on it. Thanks!

**Comment by bufferbandit** [comment]
Looks like the update to RM2FB in the commit fixed it. Thanks!

**Comment by briankaemingk** [comment]
It works now for me as well. Thanks!
