### ISSUE TITLE
2.15.0.1667 RM2FB issues

### ISSUE THREAD

**Issue by jimbolaya** [ddvk/remarkable-autoinstall#24]
When I swipe up, it just restarts the xochitl interface.

From journalctl, it shows:

```
Oct 18 16:35:12 reMarkable touchinjector[381]: STARTING RM2FB
Oct 18 16:35:12 reMarkable touchinjector[381]: Missing address for function 'getInstance'
Oct 18 16:35:12 reMarkable touchinjector[381]: PLEASE SEE https://github.com/ddvk/remarkable2-framebuffer/issues/18
```

That particular issue has a solution at the end (as I'm looking at it). I'm not sure how to reference a thread in a different project, but this worked for me.

Thanks to the steps of @snelg !! They are working for me.

cat << EOF > /etc/rm2fb.conf
!20221003075633
version str 2.15.0.1067
update addr 0x4e425c
updateType str QRect
create addr 0x4e6e80
shutdown addr 0x4e6e18
wait addr 0x4e5e20
getInstance addr 0x4dade4
EOF

**Comment by ddvk** [comment]
I updated the script to use the latest rm2fb version, try again

**Comment by jimbolaya** [comment]
Works great! Thank you.
