### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by juanfcocontreras** [ddvk/remarkable-autoinstall#5]
I have a question about the two ways to install KOReader. In the instructions, @ddvk mentions that:

"This will not touch xochitl, thus it should be pretty safe"

I should understand that the installation script does modify xochitl? if I understood it correctly, the script copies a series of files (without replacing anything) to the Remarkable, and then enables a service. Why is it safer to use toltec?

Sorry for these questions if they are very basic and thanks in advance.

**Comment by ddvk** [comment]
this script doesnt disable xochitl, it just adds an additional service that listens for a specific gesture, thus it is minimaly invasive. (most common "bricking" is people disabling xochitl and not remembering the password, or doing factory reset which also resets the password)

toltec is more streamlined, has more features, but imho it is for users with some basic linux knowledge.

**Comment by juanfcocontreras** [comment]
Thanks @ddvk , I misunderstood your instructions.

Sorry for the inconvenience and thanks for your great contribution!
