### ISSUE TITLE
Does the auto.sh compaitable with Remarkable2?

### ISSUE THREAD

**Issue by januslinhc** [ddvk/remarkable-autoinstall#7]
I have executed https://raw.githubusercontent.com/ddvk/remarkable-autoinstall/master/auto.sh on my remarkable2 but seems like it doesnt work. Im not able to launch the draft. So is it compatible on remarkable 2? If not, how can i revert back? Thank you for your help.

**Comment by teranex** [comment]
I also just tried it but some files could not be downloaded:

```
reMarkable: ~/ sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-autoinstall/master/rm2/auto_rm2.sh -O-)" 
Connecting to raw.githubusercontent.com (151.101.128.133:443)
wget: note: TLS certificate validation not implemented
-                    100% |****************************|  1703  0:00:00 ETA
Failed to stop touchinjector.service: Unit touchinjector.service not loaded.
Downloading files...
Connecting to build.koreader.rocks (172.67.175.187:80)
wget: server returned error: HTTP/1.1 404 Not Found
```

**Comment by JadeJitsu** [comment]
For the reMarkable 2 you should be using this (found here: https://github.com/ddvk/remarkable-autoinstall/tree/master/rm2):

sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-autoinstall/master/rm2/auto_rm2.sh -O-)"

**Comment by teranex** [comment]
> For the reMarkable 2 you should be using this (found here: https://github.com/ddvk/remarkable-autoinstall/tree/master/rm2):
> 
> sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-autoinstall/master/rm2/auto_rm2.sh -O-)"

I might overlook something, but that is the same command as I used?

**Comment by Schroedi** [comment]
The nightly build of koreader, that is referenced in the install script, is no longer available at that URL. 
Here is a list of available builds: http://build.koreader.rocks/download/nightly

You can install the build from today like this on your remarkable(2) after you ran the install script from this repositoy:
```
APPDIR=${APPDIR:-/home/root/apps}
KOREADER="http://build.koreader.rocks/download/nightly/v2020.12-114-g4b02edc_2021-01-14/koreader-remarkable-v2020.12-114-g4b02edc_2021-01-14.zip"
wget "$KOREADER" -O /tmp/koreader.zip
unzip /tmp/koreader.zip -d $APPDIR
```

**Comment by teranex** [comment]
@Schroedi thanks I got it working :)

**Comment by ddvk** [comment]
no, auto.sh is for rm1 only, i've updated the readme
